name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1


    - name: Fetch tags and master for GitVersion
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master

    - name: GitVersion
      id: GitVersion
      uses: ./ # Uses an action in the root directory

    - name: Output
      run: 'echo "NuGetVersionV2: ${{ steps.GitVersion.outputs.GitVersion_NuGetVersionV2 }}"'

#    - name: GitVersion
#      uses: docker://gittools/gitversion:5.0.2-linux
#      with:
#        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_NuGetVersionV2\\r\\n$GitVersion_AssemblySemVer\\r\\n$GitVersion_MajorMinorPatch\\r\\n$GitVersion_InformationalVersion > /github/workspace/version.txt\""
 
